version: 2.1

### Context Setup
# AWS_ACCESS_KEY_ID
# AWS_DEFAULT_REGION=ap-southeast-2
# AWS_REGION=ap-southeast-2
# AWS_SECRET_ACCESS_KEY
# AWS_ACCOUNT_ID

executors:
  node-executor:
    docker:
      - image: circleci/node:10

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
         name: build
         command: |
           sudo npm install -g aws-cdk
           npm ci
           npm audit
           npm run lint
           npm run build
           cdk synth
           cdk diff || echo "ok"

  deploy:
    executor: node-executor
    steps:
      - checkout
      - run:
         name: deploy
         command: |
           sudo npm install -g aws-cdk
           npm ci
           npm run build
           cdk diff || echo "ok"
           cdk deploy --require-approval=never

workflows:
  build:
    jobs:
      - build:
          name: build_dev
          context: DevContext
      - approval:
          type: approval
          requires:
            - build_dev
          filters:
            branches:
              only: master
      - deploy:
          name: deploy_dev
          context: DevContext
          requires:
            - approval
          filters:
            branches:
              only: master
